### ISSUE TITLE
error ao executar script

### ISSUE THREAD

**Issue by tuxjr** [MrEmpy/EHoney#1]
Traceback (most recent call last):                                                                                                                                     
  File "/home/kali/Documents/EHoney/./EHoney.py", line 354, in <module>                                                                                                
    main()                                                                                                                                                             
  File "/home/kali/Documents/EHoney/./EHoney.py", line 72, in main                                                                                                     
    import config.web as web                                                                                                                                           
  File "/home/kali/Documents/EHoney/config/web.py", line 33, in <module>                                                                                               
    Run(host='127.0.0.1', port=int(linecache.getline('/etc/ehoney/config/ports.conf', 5).split('=')[1]))                                                               
IndexError: list index out of range

**Comment by brosck** [comment]
Baixe o EHoney novamente e execute o "install.sh" como root. Creio que o problema tenha sido corrigido.

**Comment by tuxjr** [comment]
[01] Start FTP Honeypot
    [02] Start Telnet Honeypot
    [03] Start Web Honeypot
    [04] Create Report
    
Select: 3
[*] Honeypot is starting, good hunting ;)
[+] Honeypot started!                                                                                                                                                  
                                                                                                                                                                       
Traceback (most recent call last):                                                                                                                                     
  File "/home/kali/Documents/EHoney/./EHoney.py", line 354, in <module>                                                                                                
    main()                                                                                                                                                             
  File "/home/kali/Documents/EHoney/./EHoney.py", line 72, in main                                                                                                     
    import config.web as web                                                                                                                                           
  File "/home/kali/Documents/EHoney/config/web.py", line 33, in <module>                                                                                               
    Run(host='127.0.0.1', port=int(linecache.getline('/etc/ehoney/config/ports.conf', 5).split('=')[1]))                                                               
IndexError: list index out of range

**Comment by tuxjr** [comment]
Estranho, mesmo erro. Deletei e dei um Git novamente, executado como root.

**Comment by tuxjr** [comment]
Vou tentar outra coisa aqui..

**Comment by brosck** [comment]
Estranho, eu refiz os passos aqui da instalação e não ocorreu nenhum erro. Executei usando o python 3.10.1.

**Comment by tuxjr** [comment]
File "/home/kali/Documents/EHoney/./EHoney.py", line 354, in <module>                                                                                                             
    main()                                                                                                                                                                          
  File "/home/kali/Documents/EHoney/./EHoney.py", line 60, in main                                                                                                                  
    import config.ftp as ftp                                                                                                                                                        
  File "/home/kali/Documents/EHoney/config/ftp.py", line 81, in <module>                                                                                                            
    Run(host='127.0.0.1', port=int(linecache.getline('/etc/ehoney/config/ports.conf', 3).split('=')[1]))                                                                            
  File "/home/kali/Documents/EHoney/config/ftp.py", line 52, in __init__                                                                                                            
    if resposta:

**Comment by tuxjr** [comment]
Vou entao baixar esta versao que vc esta usando do python

**Comment by brosck** [comment]
Baixa e depois me diz se funcionou.

**Comment by tuxjr** [comment]
Nada...Estou rodando em um kali, nao sei se isso interfere, mas irei criar agora uma vm na aws e testar la pra ver se da certo..

**Comment by tuxjr** [comment]
Mr, por acaso vc esta testando em qual distribuição linux ? Voltei a testar aqui com outro linux, Debian 11, instalei esse servidor limpo, rodei o ./install.sh mesmo assim nao foi..

root@clone:~/EHoney# ./EHoney.py
Traceback (most recent call last):
  File "/root/EHoney/./EHoney.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@clone:~/EHoney#

**Comment by tuxjr** [comment]
root@clone:~/EHoney# ./EHoney.py
Traceback (most recent call last):
  File "/root/EHoney/./EHoney.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
root@clone:~/EHoney#

**Comment by tuxjr** [comment]
./EHoney.py
Traceback (most recent call last):
  File "/root/EHoney/./EHoney.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by brosck** [comment]
Você tem o pip instalado ? Se tiver entra no diretório do EHoney e digita

```
pip install -r requirements.txt
```

O diretório /etc/ehoney foi criado ?

**Comment by tuxjr** [comment]
pip install -r requirements.txt
Requirement already satisfied: colorama in /usr/local/lib/python3.9/dist-packages (from -r requirements.txt (line 1)) (0.4.4)
cd /etc/ehoney/
config  logs  reports  web

**Comment by brosck** [comment]
Então dps do "pip install -r requirements.txt" tenta executar o "./EHoney.py" ou "ehoney"

**Comment by tuxjr** [comment]
quando executo "ehoney" ou "./EHoney.py" da esse erro:

Traceback (most recent call last):
  File "/usr/bin/ehoney", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

Traceback (most recent call last):
  File "/root/EHoney/./EHoney.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by brosck** [comment]
Digita ```pip install requests``` e depois executa novamente

**Comment by tuxjr** [comment]
Vou refazer tudo do zero novamente.. Quando roda o script ./install.sh já baixa automaticamente o Python?

**Comment by brosck** [comment]
Sim, ele já instalado todos os requisitos.

**Comment by tuxjr** [comment]
Estranho, estou subindo outro debian do zero aqui, irei refazer.Nem irei instalar o Python, vou rodar pelo script entao..Assim ele já instala.

**Comment by tuxjr** [comment]
Neste exemplo setei opção 3, porem mesmo tentando acessar via navegador o ip nada ocorre..Precisa instalar apache, ou estou fazendo errado..

precisa abrir porta 80 com iptables?

**Comment by tuxjr** [comment]
[Tool created by MrEmpy]
           [Version 1.0]

    [01] Start FTP Honeypot
    [02] Start Telnet Honeypot
    [03] Start Web Honeypot
    [04] Create Report

Select: 3
[*] Honeypot is starting, good hunting ;)
[+] Honeypot started!

**Comment by brosck** [comment]
Não precisa instalar o apache. Na minha VPS eu usei o ufw para abrir a porta 21 externamente, talvez esse seja o problema. Isso acontece com as outros serviços do EHoney ?

**Comment by tuxjr** [comment]
Tambem, nenhum serviço responde, ftp, telnet e serviço web..

**Comment by brosck** [comment]
Deve ser este o problema.
